align.preset = none
binPack.preset = false
maxColumn = 80
rewrite.scala3.convertToNewSyntax = true
rewrite.scala3.removeOptionalBraces = no
runner.dialect = scala213
trailingCommas = always
version = 3.11.0
