# log4j2's own
dest=err
status=warning
name=PropertiesConfig

# Console logging config
appender.console.layout.pattern=%p\t[%T]\t%c{10}\t%m%n
appender.console.layout.type=PatternLayout
appender.console.name=STDOUT
appender.console.type=Console

rootLogger.appenderRef.stdout.ref=STDOUT
rootLogger.level=debug

# Silence specific noisy packages
logger.hadoop.name=org.apache.hadoop
logger.spark.level=error
logger.spark.name=org.apache.spark
logger.hadoop.level=error
logger.sparkproject.name=org.sparkproject
logger.sparkproject.level=error
logger.netty.name= io.netty
logger.netty.level=error
logger.parquet.name=org.apache.parquet
logger.parquet.level=error
